-- Atividade 4: Update e Delete

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(50),
    CIDADE VARCHAR2(50),
    IDADE NUMBER
);

SELECT * FROM CLIENTES;

INSERT INTO CLIENTES (ID_CLIENTE,NOME_CLIENTE,CIDADE,IDADE)
VALUES (1,'Vitor','Gameleira',21);

INSERT INTO CLIENTES (ID_CLIENTE,NOME_CLIENTE,CIDADE,IDADE)
VALUES (2,'Diego','Recife',35);

INSERT INTO CLIENTES (ID_CLIENTE,NOME_CLIENTE,CIDADE,IDADE)
VALUES (3,'Torres','Bunga',24);


SELECT NOME_CLIENTE,IDADE FROM CLIENTES
WHERE IDADE > 25;


UPDATE CLIENTES
SET CIDADE = 'Palmares'
WHERE ID_CLIENTE = 3;

DELETE FROM CLIENTES
WHERE ID_CLIENTE = 1;


COMMIT;
