-- ATIVIDADE 8

CREATE TABLE ESTOQUE (
    ID_ITEM NUMBER PRIMARY KEY,
    PRODUTO VARCHAR2(50),
    QUANTIDADE NUMBER,
    PRECO NUMBER(10,2)
);

INSERT INTO ESTOQUE (ID_ITEM, PRODUTO, QUANTIDADE, PRECO)
VALUES (1, 'Mouse Gamer', 15, 120);

INSERT INTO ESTOQUE (ID_ITEM, PRODUTO, QUANTIDADE, PRECO)
VALUES (2, 'Teclado Mecânico', 7, 350);

INSERT INTO ESTOQUE (ID_ITEM, PRODUTO, QUANTIDADE, PRECO)
VALUES (3, 'Headset', 20, 250);


UPDATE ESTOQUE
SET QUANTIDADE = QUANTIDADE - 5
WHERE ID_ITEM = 3;


DELETE FROM ESTOQUE
WHERE QUANTIDADE < 10;


SELECT PRODUTO, PRECO FROM ESTOQUE
ORDER BY PRECO ASC;
