-- Atividade 6

CREATE TABLE VENDAS (
    ID_VENDA NUMBER PRIMARY KEY,
    CLIENTE VARCHAR2(50),
    VALOR NUMBER,
    DATA_VENDA DATE
);

INSERT INTO VENDAS (ID_VENDA,CLIENTE,VALOR,DATA_VENDA)
VALUES (1,'Vitor',5000,TO_DATE('15/10/1999','DD/MM/YYYY'));

INSERT INTO VENDAS (ID_VENDA,CLIENTE,VALOR,DATA_VENDA)
VALUES (2,'Diego',18000,TO_DATE('21/03/2004','DD/MM/YYYY'));

INSERT INTO VENDAS (ID_VENDA,CLIENTE,VALOR,DATA_VENDA)
VALUES (3,'Torres',500,TO_DATE('30/12/2015','DD/MM/YYYY'));

UPDATE VENDAS
SET VALOR = 5500
WHERE ID_VENDA = 1;


DELETE FROM VENDAS
WHERE ID_VENDA = 2;

SELECT SUM (VALOR) AS VALOR_TOTAL FROM VENDAS;

SELECT MAX(VALOR) AS MAIOR_VALOR_DE_VENDA FROM VENDAS;

COMMIT;