-- ATIVIDADE 7

CREATE TABLE EMPREGADOS (
    ID_EMPREGADO NUMBER PRIMARY KEY,
    NOME VARCHAR2(50),
    CARGO VARCHAR2(50),
    SALARIO NUMBER(10,2)
);

INSERT INTO EMPREGADOS (ID_EMPREGADO, NOME, CARGO, SALARIO)
VALUES (1, 'Vitor', 'Analista', 2500);

INSERT INTO EMPREGADOS (ID_EMPREGADO, NOME, CARGO, SALARIO)
VALUES (2, 'Diego', 'Gerente', 7000);

INSERT INTO EMPREGADOS (ID_EMPREGADO, NOME, CARGO, SALARIO)
VALUES (3, 'Torres', 'Estagiário', 1200);


UPDATE EMPREGADOS
SET SALARIO = SALARIO * 1.15
WHERE ID_EMPREGADO = 3;


SELECT NOME, SALARIO FROM EMPREGADOS
WHERE SALARIO > 3000;


SELECT * FROM EMPREGADOS
ORDER BY SALARIO DESC;

COMMIT;