-- SUBQUERY == SUBSELECT OU SUB CONSULTA


-- UMA SUBQUERY É UMA INSTRUÇÃO DO TIPO SELECT DENTRO DE OUTRA INSTRUÇÃO SQL


-- UM POUCO CONFUSO, NÉ ? MAS IREMOS ENTENDER MELHOR FAZENDO UM EXEMPLO


-- VER REGISTROS DA TABELA ALUNOS
SELECT * FROM ALUNOS;

-- MUDAR O NOME DA COLANA PESO DENTRO DE ALUNO
ALTER TABLE ALUNOS
RENAME COLUMN PESO TO PESO_ALUNO;


-- VER APENAS A COLUNA PESO DA TABELA ALUNOS
SELECT PESO_ALUNO FROM ALUNOS;


-- VER A COLUNA PESO SOMENTE DO ALUNO VITOR
SELECT PESO_ALUNO FROM ALUNOS
WHERE NOME_ALUNO = 'Vitor';


-- VER AS COLUNAS NOME E PESO ONDE PESO_ALUNO É MAIOR QUE 99
SELECT NOME_ALUNO, PESO_ALUNO FROM ALUNOS
WHERE PESO_ALUNO > 100;


-- ATENÇÃO: ESSE SELECT EQUIVALE A 99
-- SELECT PESO_ALUNO FROM ALUNOS WHERE NOME_ALUNO = 'Vitor'; => 99


-- É RETORNADO O NOME E PESO DE TODOS OS ALUNOS QUE PESAM MAIS DO QUE A ALUNA PATRICIA
SELECT NOME_ALUNO, PESO_ALUNO FROM ALUNOS
WHERE PESO_ALUNO > (SELECT PESO_ALUNO FROM ALUNOS WHERE NOME_ALUNO = 'Vitor');
