-- FOREIGN KEY: É UMA COLUNA NUMA TABELA QUE APONTA A CHAVE PRIMARIA DE OUTRA TABELA

-- ELA CRIA UMA LIGAÇÃO ENTRE AS TABELAS

-- VAMOS VER OS REGISTROS DAS TABELAS
SELECT * FROM CIDADES;
SELECT * FROM ALUNOS;

-- VEJA QUE NA TABELA ALUNOS EXISTE A COLUNA CIDADE COM OS NOMES DAS CIDADES
-- IREMOS EXCLUIR ESSA COLUNA PARA USSARMOS OS CODIGOS DAS CIDADES E NÃO OS NOME
ALTER TABLE ALUNOS DROP COLUMN CIDADE_ALUNO;


-- AGORA IREMOS INSERIR A COLUNA CIDADE_ID
ALTER TABLE ALUNOS ADD CIDADE_ID NUMBER;


-- ADICIONAR UMA REGRA: A COLUNA CIDADE_ID SER[A UMA FOREIGN KEY
-- VAMOS ENTENDER O QUE CADA LINHA SIGNIFICA
ALTER TABLE ALUNOS           -- QUERO ALTERAR A TABELA ALUNOS
ADD CONSTRAINT FK_CIDADE_ID  -- VOU CRIAR UMA REGRA CHAMADA FK_CIDADE_ID
FOREIGN KEY (CIDADE_ID)      -- A COLUNA CIDADE_ID SERÁ UMA FOREIGN KEY
REFERENCES CIDADES (ID_CID); -- A COLUNA CIDADE_ID DEVE USAR OS VALORES CONTIDOS NA COLUNA ID_CID DA TABELA CIDADES


-- VAMOS OLHAR AS TABELAS
SELECT * FROM ALUNOS;
SELECT * FROM CIDADES;

-- AGORA VAMOS INSERIR DADOS APENAS NA COLUNA CIDADE_ID DA TABELA ALUNOS
UPDATE ALUNOS
SET CIDADE_ID = 5
WHERE ID_ALUNO = 5;

INSERT INTO CIDADES (ID_CID,NOME_CID)
VALUES (5,'PALMARES');

COMMIT;

