-- ###### CONCATENANDO COLUNAS COM O PIPE || ######


-- CONCATENAR SIGNIFICA JUNTAR

SELECT * FROM ALUNOS;


SELECT NOME_ALUNO, CIDADE_ALUNO FROM ALUNOS;

SELECT NOME_ALUNO || CIDADE_ALUNO FROM ALUNOS;


SELECT NOME_ALUNO || CIDADE_ALUNO AS NOME_CIDADE FROM ALUNOS;

-- ADICIONA UM TRAÇO ENTRE AS COLUNAS
SELECT NOME_ALUNO || ' - ' ||  CIDADE_ALUNO AS NOME_CIDADE FROM ALUNOS;

SELECT NOME_ALUNO || ' ' ||  CIDADE_ALUNO AS NOME_CIDADE FROM ALUNOS;


-- ###### MODIFICANDO TAMANHO/TIPO DA COLUNA COM ALTER TABLE MODIFY ######


DESC ALUNOS;


-- AUMENTAR O TAMNAHO DA COLUNA CIDADE_ALUNO PARA 60
ALTER TABLE ALUNOS MODIFY CIDADE_ALUNO VARCHAR2(60);


-- ALTERANDO O TIPO DA COLUNA DATA_NASC_ALUNO PARA DATE
-- OBSERVAÇÃO: A COLUNA DEVE ESTAR VAZIA
ALTER TABLE ALUNOS MODIFY DATA_NASC_ALUNO DATE;

SELECT * FROM ALUNOS;


-- ###### APAGANDO UMA COLUNA DA TABELA COM ALTER TABLE DROP ######


SELECT * FROM ALUNOS;


-- APAGAR A COLUNA CIDADE-ALUNO
ALTER TABLE ALUNOS DROP (CIDADE_ALUNO);


-- ###### DELETAR REGISTROS DA TABELA COM DELETE ######


SELECT * FROM ALUNOS;


-- DELETAR O REGISTRO EM QUE O ID_ALUNO É IGUAL A 2
DELETE FROM ALUNOS WHERE ID_ALUNO = 2;


-- ATENCAO: O DELETE PODE SER DESFEITO COM O ROLLBAKC
ROLLBACK;


-- ###### EXCLUIR TABELA COM DROP TABLE ######


-- PRIMEIRO IREMOS CRIAR UMA TABELA
CREATE TABLE ESCOLAS (
    ID_ESCOLA NUMBER,
    NOME_ESCOLA VARCHAR2 (50),
    CNPJ_ESCOLA NUMBER
);


SELECT * FROM ESCOLAS


DESC ESCOLAS


-- INSERIR REGISTROS NA TABELA ESCOLAS
INSERT INTO ESCOLAS (ID_ESCOLA,NOME_ESCOLA,CNPJ_ESCOLA)
VALUES (2,'JAIME',481359129);


-- EXCLUIR A TABELA ESCOLAS
DROP TABLE ESCOLAS;
    

