-- CHAVE PRIMARIA: É USADA P/ IDENTIFICAR DE FORMA UNICA
-- CADA REGISTRO EM UMA TABELA


-- É COMPOSTA POR UMA COLUNA QUE GARANTE QUE
-- CADA LINHA TENHA UM VALOR UNICO, IMPEDINDO
-- REGISTROS DUPLICADOS E GARANTINDO A INTEGRIDADE DOS DADOS


-- GEREALMENTE A CHAVE PRIMARIA É UMA COLUNA POR NOM ID


-- EXEMPLO:


-- ID_CID     NOME_CID
-- 1          MANAUS
-- 2          PARINTNS
-- 3          SANTAREM


-- CRIANDO A TABELA CIDADES COM PRIMATY-KEY
-- NOT NULL: GARANTE QUE A COLUNA NÃO PODE TER VALORES NULOS
-- CONSTRAINT: É UMA REGRA QUE APLICAMOS A UMA COLUNA
CREATE TABLE CIDADES (
    ID_CID NUMBER NOT NULL,
    NOME_CID VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CID)
);


-- INSERINDO REGISTROS NA TABELA CIDADES
INSERT INTO CIDADES (ID_CID,NOME_CID)
VALUES (1,'MANAUS');


-- VER  REGISTROS DA TABELA CIDADES
SELECT * FROM CIDADES;
 

-- AO INVER  DE PASSARMOS O VALOR DO ID NO INSERT USAMOS
-- UM CONCEITO CHAMADO AUTO-INCREMENTO


-- AUTO-INCREMENTO: É QUANDO UMA COLUNA PRIMARY KEY TEM A
-- CAPACIDADE DE AUMENTAR O SEU VALOR AUTOMATICAMENTE TODA
-- VEZ QUE UM NOVO REGISTRO É INSERIDO NA TABELA

-- ASSIM NÃO PRECISAMOS FORNECER ESSE VALOR MANUALMENTE

-- COMO FAZER ISSO NO ORACLE?

-- COM A AJUDA DE UMA SEQUENCE E UMA TRIGGER

-- SEQUENCE: É UM OBJETO USADO P/ GERAR NUMEROS SEQUENCIAIS UNICOS

-- SINTAXE BASICA DA SEQUENCE

-- ESSA SEQUENCIA SERÁ USADA NA COLUNA ID_CID NA TABELA CIDADES

CREATE SEQUENCE MINHA_SEQUENCIA
    START WITH 1    -- DEFINE O VALOR INICIAL DA SEQUENCIA
    INCREMENT BY 1  -- INCREMENTA EM 1 A CADA USO DA SEQUENCIA
    MAXVALUE 1000;  -- VALOR FINAL QUE A SEQUENCIA PODE ALCANÇAR  
    
-- TRIGGER: É UMA AÇÃO AUTOMATICA (GATILHO) QUE OCORRE ALGO
-- ESPECIFICO ACONTECE COMO POR EXEMPLO, QUANDO INSERIMOS UM NOVO
-- REGISTRO NA TABELA

-- SINTAXE DE UMA TRIGGER
-- O QUE ESSA TRIGGER FAZ?
-- SEMPRE QUE ALGUEM INSERIR UM NOVO REGISTRO NA TABELA CIDADES
-- E SE A COLUNA ID_CID NÃO TIVER VALOR (FOR NULO)
-- A TRIGGER GERA AUTOMATICAMENTE UM VALOR NOVO USANDO A MINHA_SEQUENCIA
-- E PREENCHE ESSE VALOR NO ID_CID

CREATE OR REPLACE TRIGGER INSERE_ID
BEFORE INSERT ON CIDADES
FOR EACH ROW
BEGIN
    IF :NEW.ID_CID IS NULL THEN
        SELECT MINHA_SEQUENCIA.NEXTVAL INTO :NEW.ID_CID FROM DUAL;
    END IF;
END;


-- VER REGISTROS DA COLUNA CIDADES
SELECT * FROM CIDADES;


-- EXCLUIR REGISTROS DA COLUNA CIDADES
TRUNCATE TABLE CIDADES;


-- TESTAR O AUTO-INCREMENTO
-- VAMOS INSERIR REGISTROS NA TABELA CIDADES
-- SEM PASSAR O ID
INSERT INTO CIDADES (NOME_CID)
VALUES ('SANTAREM');