-- ###### TRAZENDO 2 OU MAIS RESULTADOS NO SELECT COM O UNION ######


-- CRIAR TABELA PROFESSORES
CREATE TABLE PROFESSORES (
    ID_PROF NUMBER,
    NOME_PROF VARCHAR2(50),
    CIDADE_PROF VARCHAR2(50)
);
    

-- INSERIR REGISTROS NA TABELA PROFESSORES
INSERT INTO PROFESSORES (ID_PROF,NOME_PROF,CIDADE_PROF)
VALUES (6,'RAIMUNDO','BARREIRINHA');


-- VER REGISTROS DA TABELA PROFESSORES
SELECT * FROM PROFESSORES;


-- VER REGISTROS DA TABELA ALUNOS
SELECT * FROM ALUNOS;


-- TRAZENDO A COLUNA CIDADE DAS TABELAS ALUNOS E PROFESSORES
-- VEJA QUE AS CIDADES NÃO SE REPETEM
SELECT CIDADE_ALUNO FROM ALUNOS
UNION
SELECT CIDADE_PROF FROM PROFESSORES;


-- O UNION ALL TRAS TODOS OS REGISTROS INCLUSIVE OS DUPLICADOS
SELECT CIDADE_ALUNO FROM ALUNOS
UNION ALL
SELECT CIDADE_PROF FROM PROFESSORES

COMMIT;