-- LEFT JOIN

-- A REGRA DELE É: ME TRAGA TODO MANDO DA TABELA DA ESQUERDA E, SE ELES TIVEREM

-- UMA COMBINAÇÃO NA DIREITA, ME MOSTRE TAMBÉM. SE NÃO TIVEREM, TUDO BEM,

-- APENAS ME DIGA QUE NÃO ENCONTROU NADA

-- PARA FAZER ESSA COMBINAÇÃO, USAMOS UMA CHAVE EM COMUM, QUE NO NOSSO CASO, É À COLINA TD ALUNO, FOIS ESSA COLINA ESTÁ PRESENTE NAS DUAS TABEIAS

-- A CONSULTA FICA QUASE IGUAL, SÓ MUDAHOS O TIPO DE JOIN

SELECT ALUNOS.NOME, MATRICULAS.ATIVIDADE -- VER A COLUNA NOME DA TABELA ALUNOS E ATIVIDADE DA TABELA MATRICULAS
FROM ALUNOS -- TABELA PRINCIPAL É ALUNOS
LEFT JOIN MATRICULAS -- TABELA SECUNDARIA É MATRICULAS
ON ALUNOS.ID = MATRICULAS.ID_ALUNO; -- COLUNA EM COMUM ENTRE AS DUAS TABELAS
