-- ROUND: SERVE PARA ARREDONDAR NUMEROS

-- SINTAXE:
-- ROUND(COLUNA,QUANTIDADE_CASAS_DECIMAIS)

CREATE TABLE PRODUTOS(
    ID      NUMBER GENERATED AS IDENTITY,
    PRODUTO    VARCHAR2(255) NOT NULL,
    PRECO  NUMBER NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

INSERT INTO PRODUTOS (PRODUTO,PRECO)
VALUES ('LEITE',5.99);

SELECT * FROM PRODUTOS;

-- ARREDONDE O PREÇO PRA MIM MANTENDO 2 CASAS DECIMAIS
SELECT PRODUTO, PRECO, ROUND(PRECO,2) AS PRECO_ARREDONDADO FROM PRODUTOS;

-- OBS: SE NÃO PASSAR O NUMERO DE CASAS DECIMAIS, ELE ARREDONDA P/ O NUMERO
-- INTEIRO MAIS PROXIMO

COMMIT;