-- SUBSTR: COM ELA, A GENTE CONSEGUE CORTAR E PEGAR APENAS UM PEDAÇO DE UM TEXTO

SELECT * FROM ALUNOS;

-- A SINTAXE DELA TEM 3 PARTES
-- SUBSTR(COLUNA,DE_ONDE_COMECAR,QUANTOS_CARACTERES_PEGAR)

SELECT
    NOME,
    SUBSTR(NOME,1,3) AS INICIAIS
FROM
    ALUNOS;
    
-- OBS: O TERCEIRO ARGUMENTO É OPCIONAL. SE VOCE NÃO COLOCAR, ELE PEGA TUDO DO 
-- INICIO ATE O FINAL DO TEXTO

-- VAMOS JUNTAR INSTR E SUBSTR PARA RESOLVER UM PROBLEMA REAL


-- USANDO NOSSA TABELA DE CLIENTES, EU QUERO EXTRAIR APENAS O NOME DE USUARIO
-- DE CADA EMAIL, OU SEJA, TUDO O QUE VEM ANTES DO @

-- PRIMEIRO, USAMOS O INSTR PARA DESCOBRIR A POSICAO DO @

-- DEPOIS, USAMOS O SUBSTR PARA PEGAR O TEXO, COMEÇANDO DA POSIÇÃO 1 ATÉ A 
-- POSIÇÃO ANTES DO @

SELECT
    EMAIL
    SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1) AS USUARIO
FROM
    CLIENTES
WHERE
    EMAIL IS NOT NULL;

