-- TO_CHAR: PEGA UMA DATA QUE JÁ ESTÁ NO FORMATO DO ORACLE E A 
-- CONVERTE PARA UM TEXTO, ESTILIZADO DE FORMA QUE VOCE MANDAR

-- A SINTAXE É:
-- TO_CHAR(COLUNA_DE_DATA, 'FORMATO_DE_SAIDA')

SELECT
    DATA_NASCIMENTO,
    TO_CHAR(DATA_NASCIMENTO, 'DD/MM/YYYY') AS FORMATO_BR,
    TO_CHAR(DATA_NASCIMENTO, 'YYYY-MM-DD') AS FORMATO_ISO,
    TO_CHAR(DATA_NASCIMENTO, 'DAY, DD "DE" MONTH') AS POR_EXTENSO
FROM
    CLIENTES
WHERE
    ID = 1;
    
    COMMIT;