-- TO_DATE: ELA CONVERTE UMA STRING EM UM DADO DO TIPO DATE

-- A SINTAXE É:
-- TO_DATE('TEXTO','FORMATO')

-- O FORMATO É A PARTE MAIS IMPORTANTE. OS CODIGOS MAIS COMUNS SÃO:

-- DD: DIA COM 2 DIGITOS - 01, 02, 15
-- MM: MES COM 2 DIGITOS - 01, 07, 12
-- YYYY: ANO COM 4 DIGITOS - 1990, 2025

CREATE TABLE CLIENTES(
    ID      NUMBER GENERATED AS IDENTITY,
    NOME   VARCHAR2(255),
    DATA_NASCIMENTO  DATE,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID)
);


INSERT INTO CLIENTES (NOME, DATA_NASCIMENTO)
VALUES ('JOAO',TO_DATE('15/10/1990', 'DD/MM/YYYY'));

SELECT * FROM CLIENTES;

COMMIT;