-- TRUNC: DE TRUNCAR. ELE SIMPLESMENTE CORTA AS CASAS DECIMAIS

-- SINTAXE:
-- TRUNC(COLUNA, QUANTIDADE_CASAS_DECIMAIS)

SELECT * FROM PRODUTOS;

SELECT PRODUTO, PRECO, TRUNC(PRECO,1) AS PRECO_TRUNC FROM PRODUTOS;

-- OBS: SE USAR TRUNC(PRECO), SEM O NUMERO DE CASAS, ELE REMOVE
-- TODA A PARTE DECIMAL. TE DANDO SO A PARTE INTEIRA DO NUMERO