-- ATIVIDADE 10

CREATE TABLE FUNCIONARIOS2 (
    ID_FUNC NUMBER PRIMARY KEY,
    NOME VARCHAR2(50),
    CARGO VARCHAR2(50),
    SALARIO NUMBER(10,2),
    DATA_ADMISSAO DATE
);

INSERT INTO FUNCIONARIOS2 (ID_FUNC, NOME, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (1, 'Ana', 'Gerente', 7000, TO_DATE('10/08/2015','DD/MM/YYYY'));

INSERT INTO FUNCIONARIOS2 (ID_FUNC, NOME, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (2, 'Carlos', 'Vendedor', 2500, TO_DATE('05/02/2020','DD/MM/YYYY'));

INSERT INTO FUNCIONARIOS2 (ID_FUNC, NOME, CARGO, SALARIO, DATA_ADMISSAO)
VALUES (3, 'Mateus', 'Vendedor', 3000, TO_DATE('12/09/2018','DD/MM/YYYY'));

COMMIT;
