-- ATIVIDADE 9

CREATE TABLE ESTOQUE (
    ID_PRODUTO NUMBER PRIMARY KEY,
    NOME VARCHAR2(50),
    QUANTIDADE NUMBER,
    PRECO NUMBER(10,2)
);

INSERT INTO ESTOQUE (ID_PRODUTO, NOME, QUANTIDADE, PRECO)
VALUES (1, 'Monitor', 12, 850);

INSERT INTO ESTOQUE (ID_PRODUTO, NOME, QUANTIDADE, PRECO)
VALUES (2, 'Teclado', 30, 120);

INSERT INTO ESTOQUE (ID_PRODUTO, NOME, QUANTIDADE, PRECO)
VALUES (3, 'Mouse', 50, 80);



COMMIT;
