-- ATIVIDADE 5

CREATE TABLE LIVROS( 
ID_LIVRO NUMBER PRIMARY KEY,
TITULO VARCHAR2(100),
PRECO NUMBER(10,2),
ANO_PUBLICACAO NUMBER
);


SELECT * FROM LIVROS;

INSERT INTO LIVROS (ID_LIVRO,TITULO,PRECO,ANO_PUBLICACAO) 
VALUES (1,'One Piece',2500,2025);

INSERT INTO LIVROS (ID_LIVRO,TITULO,PRECO,ANO_PUBLICACAO) 
VALUES (2,'Dragon BALL',550,1999);

INSERT INTO LIVROS (ID_LIVRO,TITULO,PRECO,ANO_PUBLICACAO) 
VALUES (3,'NARUTO',5,2011);

-- Aumento de 10%

UPDATE LIVROS
SET PRECO = 5.5
WHERE ID_LIVRO = 3;

SELECT PRECO
FROM LIVROS
ORDER BY PRECO DESC;

COMMIT;
