-- DESCRIEBE OS DESC: OBTEM INFORMAÇÕES DA TABEL
-- ALTER TABLE ADD: ADICIONA UMA NOVA COLUNA NA TABELA
-- DISTINCT: ELIMINA REGISTROS DUPLICADOS
-- UPDATE: ALTERAR/ATUALIZAR ALGUM DADO NOS REGISTROS


-- ## DESCRIBE ##


DESCRIBE ALUNOS;

DESC ALUNOS;


--## ALTER TABLE ADD ##


-- ADICIONAR A COLUNA CIDADE NA TABELA ALUNOS


-- LÊ-SE: ALTERAR A TABELA ALUNOS / ADICIONAR A COLUNA CIDADE_ALUNO
ALTER TABLE ALUNOS ADD CIDADE_ALUNO VARCHAR2(20);


-- VER COMO FICOU
SELECT * FROM ALUNOS;

-- ATUALIZAR OS REGISTROS NA COLUNA CIDADE_ALUNO
UPDATE ALUNOS
SET CIDADE_ALUNO = 'NIGHT-CITY'
WHERE ID_ALUNO = 4;


-- VER COMO FICOU
SELECT * FROM ALUNOS;


-- ## DISTINCT ##


-- COM ESSE SELECT QUEREMOS VER APENAS A COLUNA CIDADE_ALUNO
-- PODEMOS VER QUE TEMOS 2 CIDADES SE REPETINDO
SELECT CIDADE_ALUNO FROM ALUNOS;


-- COM O DISTINCT PODEMOS REMOVER AS DUPLICIDADES
SELECT DISTINCT(CIDADE_ALUNO) FROM ALUNOS;


-- ATENÇÃO: AS DUPLICATAS NÃO SERAO REMOVIDAS DA TABELA
-- SOMENTE NA NOSSA CONSULTA
SELECT * FROM ALUNOS;
