-- ORDER BY: ORDERNA OS DADOS DE FORMA CRESCENTE OU DECRESCENTE
-- WHERE: FILTRA A BUSCA DE DADOS.

-- VER OS REGISTROS DA TABELA ALUNOS
SELECT * FROM ALUNOS;


-- ORDER BY CRESCENTE
SELECT * FROM ALUNOS
ORDER BY NOME_ALUNO;

-- ORDER BY DECRESCENTE
SELECT * FROM ALUNOS
ORDER BY NOME_ALUNO DESC;

-- WHERE

-- SELECIONAR OS ALUNOS ONDE O SEXO É MASCULINO
SELECT * FROM ALUNOS
WHERE SEXO_ALUNO = 'M';

-- ATENÇÃO: O SQL ORACLE É CASE SENSITIVE, OU SEJA, DIFERENCIA
-- MAISCULO DE MINUSCULO

-- ATENÇÃO: A COLUNA SEXO_ALUNO É DO TIPO VARCHAR (TEXTO), ENTAO
-- NO FILTRO O M DEVE ESTAR ENTRE ASPAS SIMPLES


-- SELECIONAR OS ALUNOS ONDE O ID É IGUAL A 2
SELECT * FROM ALUNOS
WHERE ID_ALUNO = 2;

-- ATENCAO: A COLUNA ID_ALUNO É DO TIPO NUMBER, ENTAO NO FILTRO
-- O VALOR 2 NAO PODE ESTAR ENTRE ASPAS

-- PODEMOS APRIMORAR OS FILTROS USANDO OPERADORES


-- MAIOR >
-- MENOR <
-- DIFERENTE <>
-- AND
-- OR
-- IN
-- BETWEEN
-- LIKE


-- SELECIONE OS ALUNOS ONDE O ID É MAIOR QUE 3
SELECT * FROM ALUNOS
WHERE ID_ALUNO > 3;

-- SELECIONE OS ALUNOS ONDE O ID É MENOR QUE 3
SELECT * FROM ALUNOS
WHERE ID_ALUNO < 3;

-- SELECIONE OS ALUNOS ONDE O SEXO É DIFERENTE DE MASCULINO
SELECT * FROM ALUNOS
WHERE SEXO_ALUNO <> 'M';


-- SELECIONE OS ALUNOS ONDE O SEXO É MASCULINO E O ID É MAIOR QUE 3
SELECT * FROM ALUNOS
WHERE SEXO_ALUNO = 'M' AND ID_ALUNO > 3;


-- SELECIONE OS ALUNOS ONDE O ID É 2 OU 4
SELECT * FROM ALUNOS
WHERE ID_ALUNO = 2 OR ID_ALUNO = 4;


-- SELECIONAR OS ALUNOS ONDE OS VALORES 2 E 3 ESTEJAM CONTIDOS
-- NA COLUNA ID_ALUNO
SELECT * FROM ALUNOS
WHERE ID_ALUNO IN (2,3);


-- SELECIONE OS ALUNOS ONDE O VALOR DA COLUNA ID_ALUNO
-- SEJA ENTRE 2 E 4
SELECT * FROM ALUNOS
WHERE ID_ALUNO BETWEEN 2 AND 4;

-- SELECIONE OS ALUNOS ONDE NOME_ALUNO COMECE COM A LETRA C
SELECT * FROM ALUNOS
WHERE NOME_ALUNO LIKE 'C%';


-- SELECIONE OS ALUNOS ONDE NOME_ALUNO COMECE COM A LETRA P
-- AQUI O PERCENTUAL REPRESENTA O RESTO DA PALAVRA
SELECT * FROM ALUNOS
WHERE NOME_ALUNO LIKE 'P%';


-- SELECIONE OS ALUNOS ONDE NOME_ALUNO TERMINE COM A LETRA A
--AQUI O PERCENTUAL REPRESENTA O INICIO DA PALAVRA
SELECT * FROM ALUNOS
WHERE NOME_ALUNO LIKE '%a';

