-- ###### AGRUPANDO REGISTROS COM GROUP BY ######


-- VER REGISTROS NA TABELA ALUNOS
SELECT * FROM ALUNOS;


-- AGRUPAR REGISTROS DA COLUNA CIDADE_ALUNO
SELECT CIDADE_ALUNO FROM ALUNOS GROUP BY CIDADE_ALUNO;


-- AGRUPAR REGISTROS DA COLUNA CIDADE_ALUNO E CONTAR
SELECT CIDADE_ALUNO, COUNT(*) FROM ALUNOS GROUP BY CIDADE_ALUNO;


-- PODEMOS MUDAR O NOME DA COLUNA COM O AS
-- ATENÇÃO: O AS É SOMENTE UM APELIDO
SELECT CIDADE_ALUNO AS CIDADE, COUNT(*) AS QUANTIDADE FROM ALUNOS GROUP BY CIDADE_ALUNO;


-- PODEMOS USAR OUTRAS FUNÇÕES: COUNT, SUM, AVG, MAX, MIN ...
-- AGRUPAR REGISTROS DA COLUNA CIDADE_ALUNO E SOMAR PESO_ALUNO
SELECT CIDADE_ALUNO AS CIDADE, SUM(PESO) AS TOTAL_PESO FROM ALUNOS GROUP BY CIDADE_ALUNO;


-- PODEMOS INSERIR O ORDER BY PARA ORDENAR A COLUNA
-- O 1 SIGNIFICA QUE OS REGISTROS SERAO ORDENADOS PELA PRIMEIRA COLUNA DO SELECT
SELECT CIDADE_ALUNO AS CIDADE, SUM(PESO) AS TOTAL_PESO FROM ALUNOS GROUP BY CIDADE_ALUNO ORDER BY 1;

COMMIT;
