-- REVISANDO O QUE É PRIMARY KEY (CHAVE PRIMARIA)

-- É UM IDENTIFICADOR UNICO: CADA REGISTRO TEM UM NUMERO SÓ SEU QUE NÃO SE REPETE
-- NÃO EXISTEM DOIS REGISTROS COM O MESMO NUMERO

-- A PRIMARY KEY NUNCA ESTA VAZIA: NENHUMA REGISTRO PODE FICAR SEM UM NUMERO

-- GERALMENTE A CHAVE PRIMARIA É UMA COLUNA EM UMA TABELA QUE GARANTE QUE CADA LINHA SEJA UNICA

-- IMAGINE UMA SALA DE AULA CHEIA DE ALUNOS. VARIOS ALUNOS PODEM TER O NOME DE JOAO
-- COMO VOCE PODE TER CERTEZA QUE ESTA FALANDO COM O JOAO CERTO ?

-- A PRIMARY KEY É COMO O NUMERO DE MATRICULA DE CADA ALUNO

-- OQUE É AUTO INCREMENTO ?

-- A PRINCIPAL FUNCAO DO AUTO INCREMENTO É GERAR A CHAVE PRIMARIA DE FORMAR AUTOMATICA E SEGURA

-- LEMBRE-SE QUE A CHAVE PRIMARIA PRECISA SER UM NUMERO UNICO. SE VOCE TIVESSE QUE ADICIONAR
-- ESSE NUMERO MANUALMENTE, TALVEZ PODERIA COMETER ERROS

-- VAMOS CRIAR A TABELA ALUNOS, INSERINDO ESSA IDEIA DE AUTO INCREMENTEO NA COLUNA ID
-- PARA ESSES VALORES SEREM GERADOS AUTOMATICAMENTE A CADA REGISTRO NOVO INSERIDO NA TABELA

-- A FORMA MAIS MODERNA DE IMPLEMENTAR O AUTO INCREMENTO EM ORACLE (A PARTIR DA VERSAO 12C)
-- É USANDO COLUNAS DE IDENTIDADE (IDENTITY COLUMNS)

-- VOCE SIMPLESMENTE ADICIONA A CLAUSULA GENERATED AS IDENTITY A SUA COLUNA DE CHAVE PRIMARIA
CREATE TABLE ALUNOS(
    ID      NUMBER GENERATED AS IDENTITY,
    NOME    VARCHAR2(255) NOT NULL,
    CIDADE  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ALUNOS PRIMARY KEY (ID)
);

-- ANTES DE EXECUTARNMOS ESSE COMANDO VAMOS RELEMBRAR O QUE É O NOT NULL E O CONSTRAINT

-- A RESTRICAO NOT NULL GARANTE QUE À COLUNA NÃO POSSA SER VAZIA

-- O COMANDO CONSTRAINT PRALUNOS PRIMARY KEY (ID) SIGNIFICA OQUE TEREMOS UMA REGRA CHAMADA

-- PK_ALUNOS QUE DIZ QUE À COLUNA ID SERÁ UMA PRIMARY KEY

-- VER A TABELA ALUNOS
SELECT * FROM ALUNOS;

-- AGORA, PARA INSERIR UM NOVO ALUNO, VOCE NÃO INFORMA O ID. O ORACLE CUIDA DISSO PARA VOCE
INSERT INTO ALUNOS (NOME,CIDADE)
VALUES ('REBECA','FONTE NOVA');
