-- FULL JOIN

-- A REGRA DELE É: JUNTE TUDO! ME MOSTRE TODO MUNDO DA TABELA DA ESQUERDA
-- E TODO MUNDO DA TABELA DA DIREITA. ONDE HOUVER COMBINACAO, JUNTE. ONDE
--NAO HOUVER, PREENCHA COM NULO E ME MOSTRE MESMO ASSIM

-- PARA FAZER ESSA COMBINACAO, USAMOS UMA CHAVE EM COMUM, QUE NO NOSSO CAS
-- É A COLUNA ID ALUNO, POIS ESSA COLUNA ESTÁ PRESENTE NAS DUAS TABELAS
-- A CONSULTA FICA QUASE IGUAL, SÓ MUDAMOS O TIPO DE JOIN

SELECT ALUNOS.NOME, MATRICULAS.ATIVIDADE 
FROM ALUNOS -- TABELA PRINCIPAL É ALUNOS
FULL JOIN MATRICULAS -- TABELA SECUNDARIA É MATRICULAS
ON ALUNOS.ID = MATRICULAS.ID; -- COLUNA EM COMUM ENTRE AS DUAS TABELAS
