-- INNER JOIN

-- A REGRA AQUI É: ME MOSTRE QUEM ESTÁ NAS DUAS TABELAS AO MESMO TEMPO

-- ELE MOSTRA A INTERSEÇÃO ENTRE AS DUAS TABELAS

-- PARA FAZER ESSA COMBINAÇÃO, USAMOS UMA CHAVE EM COMUM, QUE NO NOSSO
-- CASO É A COLUNA ID_ALUNO, POIS ESSA COLUNA ESTÁ PRESENTE NAS DUAS TABELAS

-- A CONSULTA SERIA ASSIM:

CREATE TABLE MATRICULAS(
    ID      NUMBER GENERATED AS IDENTITY,
    ID_ALUNO NUMBER(38)NOT NULL,
    ATIVIDADE    VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_MATRICULAS PRIMARY KEY (ID)
);

SELECT * FROM ALUNOS;
SELECT * FROM MATRICULAS;

INSERT INTO MATRICULAS (ATIVIDADE,ID_ALUNO)
VALUES ('NATACAO',4);

SELECT ALUNOS.NOME, MATRICULAS.ATIVIDADE -- VER A COLUNA NOME DA TABELA ALUNOS E A COLUNA ATIVIDADE DA TABELA MATRICULA
FROM ALUNOS -- TABELA PRINCIPAL É ALUNOS
INNER JOIN MATRICULAS -- TABELA SECUNDARIA É MATRICULAS
ON ALUNOS.ID = MATRICULAS.ID_ALUNO; -- COLUNA DE COMUM ENTRE AS DUAS TABELAS

DROP TABLE MATRICULAS;
