  
-- INSTR: ELA NOS AJUDA A ENCONTRAR A POSIÇÃO DE UM CARACTERE DENTRO DE OUTRO TEXTO

SELECT * FROM ALUNOS;

-- SINTAXE:
-- INSTR (COLUNA,TEXTO_QUE_VOCE_PROCURA)

SELECT 
    NOME,
    INSTR(NOME,'A') AS POSICAO_DO_A     -- É MAIS USADO PARA ACHAR O @ EM TEXTOS
FROM
    ALUNOS;
    
    
