-- LPAD E RPAD: PENSE NELAS COMO PREENCHEDORES. ELAS SERVEM PARA GARANTIR QUE UM TEXTO TENHO
-- UM TAMANHO FIXO, PREENCHENDO COM ALGUM CARACTERE QUE A GNT ESCOLHE

-- LPAD: SIGNIFICA LEFT PAD, OU SEJA, PREENCHER A ESQUERDA
-- RPAD: SIGNIFICA RIGHT PAD, OU SEJA, PREENCHER A DIREITA

-- A SINTAXE É A MESMA PARA OS DOIS:

-- LPAD (TEXTO_ORIGINAL, TAMANHO_FINAL, CARACTERE_DE_PREENCHIMENTO)
-- RPAD (TEXTO_ORIGINAL, TAMANHO_FINAL, CARACTERE_DE_PREENCHIMENTO)

-- ORACLE PEGUE O TEXTO 345 E FAÇA ELE TER O TAMANHO DE 6 CARACTERES E PREENCHA
-- OQUE FALTA COM O CARACTERE 0

SELECT
    LPAD('345',6,'0') AS CODIGO_PRODUTO
FROM DUAL -- DUAL É UMA TABELA PADRÃO P/ TESTES RAPIDOS


-- IMAGINA QUE VOCE QUER CRIAR UMA LISTA DE NOMES E QUER QUE TODOS ELES OCUPEM 20 CARACTERES
SELECT
    RPAD('RELATORIO DE VENDAS',20,'.') AS TITULO
FROM DUAL;

SELECT
    RPAD('ANA',20,'.') AS NOME_FORMATADO
FROM DUAL;

-- RECAPITULANDO

-- TRIM: NOSSO FAXINEIRO, REMOVE ESPAÇOS EM BRANCO DO INICIO E DO FIM
-- ESSENCIAL PARA LIMPEZA DE DADOS

-- LPAD: PREENCHE UM TEXTO A ESQUERDA ATE ELE ATINGIR UM TAMANHO
-- OTIMO PARA PADRONIZAR CODIGOS

-- RPAD: PREENCHE UM TEXTO A DIREITA. PERFEITO PARA ALINHAR TEXTO EM RELATORIOS.
