-- MOD: RETORNA O RESTO DE UMA DIVISÃO

-- SINTAXE:
-- MOD(NUMERO OU COLUNA, NUMERO_PELO_QUAL_DIVIDIR)

CREATE TABLE PEDIDOS(
    ID      NUMBER GENERATED AS IDENTITY,
    ID_PEDIDO   NUMBER NOT NULL,
    VALOR  NUMBER NOT NULL,
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID)
);

INSERT INTO PEDIDOS (ID_PEDIDO,VALOR)
VALUES (3,120);


SELECT * FROM PEDIDOS;

SELECT ID_PEDIDO, MOD(ID_PEDIDO, 2) AS RESTO_DA_DIVISAO_POR_2 FROM PEDIDOS;

COMMIT;
