-- RIGHT JOIN

-- A REGRA DELE É: ME TRAGA TODAS AS MATRICULAS DA TABELA DA DIREITA E,

-- SE O ALUNO CORRESPONDENTE ESTIVER NA TABELA DA ESQUERDA, ME MOSTRE

-- QUEM É. SE NÃO ESTIVER, NÃO TEM PROBLEMA

-- PARA FAZER ESSA COMBINACAO, USAMOS UMA CHAVE EM COMUM, QUE NO NOSSO

-- CASO É A COLUNA ID ALUNO, POIS ESSA COLUNA ESTÁ PRESENTE NAS PO TABELAS

-- A CONSULTA FICA QUASE IGUAL, SÓ MUDAMOS O TIPO DE JOIN

SELECT ALUNOS.NOME,MATRICULAS.ATIVIDADE -- VER A COLUNA NOME DA TABELA ALUNOS E ATIVIDADE DA TABELA MATRICULAS
FROM ALUNOS -- TABELA PRINCIPAL É ALUNOS
RIGHT JOIN MATRICULAS -- TABELA SECUNDARIA É MATRICULAS
ON ALUNOS.ID = matriculas.id_aluno; -- COLUNA EM COMUM ENTRE AS DUAS TABELAS

COMMIT;
