--  SYSDATE: RELOGIO DE PULSO DO SEU BANCO DE DADOS. SEMPRE QUE VOCE O 
-- CONSULTA, ELE TE DIZ EXATAMENTE QUE DIA E QUE HORAS SAO NAQUELE EXATO MOMENTO

SELECT SYSDATE FROM DUAL;

CREATE TABLE VENDAS(
    ID      NUMBER GENERATED AS IDENTITY,
    ID_VENDA   NUMBER NOT NULL,
    ID_CLIENTE  NUMBER NOT NULL,
    DATA_VENDA DATE,
    CONSTRAINT PK_DATA PRIMARY KEY (ID)
);

INSERT INTO VENDAS (ID_VENDA,ID_CLIENTE, DATA_VENDA)
VALUES (3,112,SYSDATE);

SELECT * FROM VENDAS;

COMMIT;
