-- ' JOÃO DA SILVA ' É DIFERENTE DE 'JOÃO DA SILVA'

-- TRIM: REMOVE TODOS OS ESPAÇOS EM BRANCO QUE ESTÃO NO INICIO E NO FINAL DE UM TEXTO

SELECT * FROM CADASTROS;

-- SINTAXE:
-- TRIM(COLUNA)

SELECT
    NOME,
    TRIM(NOME) AS NOME_CORRIGIDO
FROM
    ALUNOS;
